#!/bin/sh
mkdir -p rdtemp
pushd rdtemp >/dev/null
echo -n "extracting rdcontents... "
tar xf ../rdcontents.tar.xz
[ $? != 0 ] && echo "error" && exit 1
echo "done"
echo -n "adding maps... "
cp ../system.map .
[ $? != 0 ] && echo "error" && exit 1
echo "done"
popd >/dev/null
echo -n "creating ramdisk... "
ramdisk/mkrd initramfs-aliceos.img rdtemp/*
[ $? != 0 ] && echo "error" && exit 1
echo "done"
rm -rf rdtemp
