#!/bin/bash
if [[ ! -e ramdisk/bin/mkrd ]]; then
  pushd ramdisk >/dev/null
  echo -n "building mkrd... "
  if ( ! which clang >/dev/null ); then
    echo "you don't have clang, install it or go away"
    exit 1
  fi
  make >/dev/null
  if [ $? != 0 ]; then
    echo "error"
    exit 1
  else
    echo "done"
  fi
  popd >/dev/null
fi
mkdir -p rdtemp
pushd rdtemp >/dev/null
echo -n "extracting rdcontents... "
tar xf ../rdcontents.tar.xz
if [ $? != 0 ]; then
  echo "error"
  exit 1
else
  echo "done"
fi
popd >/dev/null
echo -n "creating ramdisk... "
ramdisk/bin/mkrd initramfs-aliceos.img rdtemp/*
if [ $? != 0 ]; then
  echo "error"
  exit 1
else
  echo "done"
fi
rm -rf rdtemp
