#!/bin/zsh
if [[ ! -e vmaliceos ]]
 then
  echo -n "building aliceos kernel... "
  if ( ! which clang >/dev/null )
   then
    echo "you don't have clang, install it or go away"
    exit 1
  fi
  if ( ! which nasm >/dev/null )
   then
    echo "you don't have nasm, please install it"
    exit 1
  fi
  ./build
  if [[ $? != 0 ]]
   then
    echo "error"
    exit 1
  else
    echo "done"
  fi
fi
if [[ ! -e initramfs-aliceos.img ]]
 then
  ./makerd
fi
QEMU="qemu-system-i386"
AOSKRNL="vmaliceos"
AOSRD="initramfs-aliceos.img"
QEMU_ARGS="-cpu 486 -m 128M -serial stdio -vga std"
if [[ ! -n $* ]]
 then
  echo "running aliceos with no commandline"
  $QEMU ${=QEMU_ARGS} -kernel $AOSKRNL -initrd $AOSRD
else
  echo "running aliceos with commandline \"$@\""
  $QEMU ${=QEMU_ARGS} -kernel $AOSKRNL -initrd $AOSRD -append "$@"
fi
