#!/bin/bash
if [[ ! -e vmaliceos ]]; then
  echo -n "building aliceos kernel... "
  if ( ! which clang >/dev/null ); then
    echo "you don't have clang, install it or go away"
    exit 1
  fi
  if ( ! which yasm >/dev/null ); then
    echo "you don't have yasm, please install it"
    exit 1
  fi
  make >/dev/null
  if [ $? != 0 ]; then
    echo "error"
    exit 1
  else
    echo "done"
  fi
fi
if [[ ! -e initramfs-aliceos.img ]]; then
  ./makerd
fi
if [[ ! -n $* ]]; then
  echo "running aliceos with no commandline"
  qemu-system-i386 -kernel vmaliceos -serial stdio -vga std -initrd initramfs-aliceos.img
else
  echo "running aliceos with commandline \"$@\""
  qemu-system-i386 -kernel vmaliceos -serial stdio -vga std -initrd initramfs-aliceos.img -append "$@"
fi
